# Generated by Django 3.2.25 on 2025-05-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=10)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(max_length=50)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('link', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rentzestimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('tax_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('zestimate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('zestimate_last_updated', models.DateField(blank=True, null=True)),
                ('zillow_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['-price'],
            },
        ),
    ]
